baseURL = 'https://tillmzw.github.io/cos'
languageCode = 'en-us'
title = 'CoS Journal'
theme = 'terminal'
defaultContentLanguage = 'en'
copyright = "© tillmzw"
enableEmoji = true

[params]
  fullWidthTheme = false
  centerTheme = true
  Toc = true
  TocTitle = "Buried Below"
  ReadMore = "follow this trail -->"

[params.logo]
  logoText = "Curse of Strahd"


[[menu.main]]
name = "Logs"
url = "/"
weight = 1

[[menu.main]]
name = "NPCs"
url = "/npcs"
weight = 2

[[menu.main]]
name = "Locations"
url = "/locations"
weight = 3

[[menu.main]]
name = "Characters"
url = "/pcs"
weight = 4

[[menu.main]]
name = "?"
url = "/about"
weight = 5
