baseURL = 'https://tillmzw.github.io/cos'
languageCode = 'de-ch'
title = 'CoS Journal'
theme = 'terminal'
defaultContentLanguage = 'de'
copyright = "© tillmzw"

[params]
  fullWidthTheme = false
  centerTheme = true
  Toc = true
  TocTitle = "Inhalt"
  ReadMore = "--> lesen"

[params.logo]
  logoText = "Curse of Strahd"



[[menu.main]]
name = "Einträge"
url = "/"
weight = 1

[[menu.main]]
name = "NPCs"
url = "/npcs"
weight = 2

[[menu.main]]
name = "Orte"
url = "/locations"
weight = 3

[[menu.main]]
name = "?"
url = "/about"
weight = 4